package com.brewery.inventoryservice.model;

public enum BeerOrderStatusEnum {

   NEW , VALIDATION_PENDING, VALIDATED , VALIDATION_FAIL,
    ALLOCATION_PENDING, ALLOCATED, ALLOCATION_EXCEPTION, CANCELED,
    DELIVERED, DELIVERED_EXCEPTION,PICKED_UP,PENDING_INVENTORY
}
