package com.main.beerorderservice.statemachine;


public enum BeerOrderEventEnum {

    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_PASSED, ALLOCATION_FAIL, ALLOCATION_PENDING_INVENTORY,
    BEER_ORDER_PICKED_UP, CANCEL_ORDER,
}
