apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    uid: tempo
    orgId: 1
    access: proxy
    editable: true
    basicAuth: false
    isDefault: false
    url: http://tempo:3100
    version: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    access: proxy
    editable: true
    url: http://gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"

