server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/BorisSpring/BreweryConfig.git"
          clone-on-start: true
          force-pull: true
          timeout: 20
          default-label: "main"
      fail-fast: true
      discovery:
        service-id: cloudconfig
        enabled: true
  profiles:
    active: "git"
  application:
    name: "cloudconfig"
management:
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  application:
    name: "Cloud config"
    onCallSupport:
      - (123) 123456789
      - (123) 987654321
    details:
      madeBy: "Boris Dimitrijevic"
      email: "borisdimitrijevicit@gmail.com"

endpoints:
  shuwdown:
    enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"